spring:
  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: Root@12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.metadata_builder_contributor: com.postgres.fulltextsearch.configurations.SqlFunctionMetaBuilderContributor
