spring:
  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:postgresql://172.17.0.2:5432/demo
    username: postgres
    password: Root@12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.metadata_builder_contributor: com.postgres.fulltextsearch.configurations.SqlFunctionMetaBuilderContributor
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false